AWSTemplateFormatVersion: 2010-09-09
Description: "Custom VPC Creation With Private and Public Subnets"

Parameters: 
  vpcstack:
    Description: Name of an active CloudFormation stack that contains the VPC
      resources.
    Type: String
    MinLength: 1
    MaxLength: 255
    AllowedPattern: "^[a-zA-Z][-a-zA-Z0-9]*$"
    Default: VPCStack
  # AvailabilityZoneA: 
    # Default: us-east-1a
    # Description: "Avaibalbility Zone 1"
    # Type: String
  # AvailabilityZoneB: 
    # Default: us-east-1b
    # Description: "Avaibalbility Zone 2"
    # Type: String
  PrivateSubnetACidr: 
    Default: 10.0.0.0/24
    Description: "Private Subnet IP Range"
    Type: String
  PublicSubnetACidr: 
    Default: 10.0.1.0/24
    Description: "Public Subnet IP Range"
    Type: String
  PrivateSubnetBCidr: 
    Default: 10.0.2.0/24
    Description: "Private Subnet IP Range"
    Type: String

Resources:
  #Private subnet for Web server
  PrivateSubnetA:
    Type: "AWS::EC2::Subnet" 
    Properties: 
      VpcId: {'Fn::ImportValue': !Sub '${vpcstack}-vpcid'}
        # - Fn::ImportValue: Fn::Sub: ${vpcstack}-vpcid
      # AvailabilityZone: !Ref AvailabilityZoneA
      AvailabilityZone: !Select 
        - 0
        - Fn::GetAZs: !Ref 'AWS::Region'
      CidrBlock: !Ref PrivateSubnetACidr
      Tags: 
        - 
          Key: Name
          Value: !Sub 'PrivateSubnetA'
  #Private subnet for App server
  PrivateSubnetB:
    Type: "AWS::EC2::Subnet" 
    Properties: 
      VpcId: {'Fn::ImportValue': !Sub '${vpcstack}-vpcid'}
        # - Fn::ImportValue: Fn::Sub: ${vpcstack}-vpcid
      # AvailabilityZone: !Ref AvailabilityZoneA
      AvailabilityZone: !Select 
        - 0
        - Fn::GetAZs: !Ref 'AWS::Region'
      CidrBlock: !Ref PrivateSubnetBCidr
      Tags: 
        - 
          Key: Name
          Value: !Sub 'PrivateSubnetB'
  PublicSubnetA: 
    Type: "AWS::EC2::Subnet"
    Properties: 
      VpcId: {'Fn::ImportValue': !Sub '${vpcstack}-vpcid'} 
        # - Fn::ImportValue: Fn::Sub: ${vpcstack}-vpcid
      # AvailabilityZone: !Ref AvailabilityZoneA
      AvailabilityZone: !Select 
        - 0
        - Fn::GetAZs: !Ref 'AWS::Region'
      CidrBlock: !Ref PublicSubnetACidr
      MapPublicIpOnLaunch: true
      Tags: 
        - 
          Key: Name
          Value: !Sub 'PublicSubnetA'
  # For the Internet Access in VPC  
  InternetGateway: 
    Type: "AWS::EC2::InternetGateway"
    Properties:
      Tags:
          - Key: Name
            Value: !Sub 'InternetGateway'
  VPCGatewayAttachment: 
    Type: "AWS::EC2::VPCGatewayAttachment"
    Properties: 
      InternetGatewayId: !Ref InternetGateway
      VpcId: {'Fn::ImportValue': !Sub '${vpcstack}-vpcid'} 
        # - Fn::ImportValue: Fn::Sub: ${vpcstack}-vpcid
  # Routing table to hold the public routes
  PublicRouteTableA: 
    Type: "AWS::EC2::RouteTable"
    Properties: 
      VpcId: {'Fn::ImportValue': !Sub '${vpcstack}-vpcid'} 
        # - Fn::ImportValue: Fn::Sub: ${vpcstack}-vpcid
      Tags: 
        - 
          Key: Name
          Value: !Sub 'PublicRouteTableA'
  PublicRoute: 
    Type: "AWS::EC2::Route"
    DependsOn: VPCGatewayAttachment
    Properties: 
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway
      RouteTableId: !Ref PublicRouteTableA
  #Associating Public Subnet to the public route table
  PublicSubnetRouteTableAssociationA: 
    Type: "AWS::EC2::SubnetRouteTableAssociation"
    Properties: 
      RouteTableId: !Ref PublicRouteTableA
      SubnetId: !Ref PublicSubnetA
  
  PrivateRouteTableA: 
    Type: "AWS::EC2::RouteTable"
    Properties: 
      VpcId: {'Fn::ImportValue': !Sub '${vpcstack}-vpcid'} 
        # - Fn::ImportValue: Fn::Sub: ${vpcstack}-vpcid
      Tags: 
        - 
          Key: Name
          Value: !Sub 'PrivateRouteTableA' 
  PrivateRouteTableB: 
    Type: "AWS::EC2::RouteTable"
    Properties: 
      VpcId: {'Fn::ImportValue': !Sub '${vpcstack}-vpcid'} 
        # - Fn::ImportValue: Fn::Sub: ${vpcstack}-vpcid
      Tags: 
        - 
          Key: Name
          Value: !Sub 'PrivateRouteTableB' 
  PrivateSubnetRouteTableAssociationA: 
    Type: "AWS::EC2::SubnetRouteTableAssociation"
    Properties: 
      RouteTableId: !Ref PrivateRouteTableA
      SubnetId: !Ref PrivateSubnetA 
  PrivateSubnetRouteTableAssociationB: 
    Type: "AWS::EC2::SubnetRouteTableAssociation"
    Properties: 
      RouteTableId: !Ref PrivateRouteTableB
      SubnetId: !Ref PrivateSubnetB
  
  #Jump box instance security group and its inbound & outbound rules
  JumpBoxSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription:
        !Sub 'Security group for JumpBox host'
      VpcId: {'Fn::ImportValue': !Sub '${vpcstack}-vpcid'} 
        # - Fn::ImportValue: Fn::Sub: ${vpcstack}-vpcid
      Tags:
        - Key: Name
          Value: !Sub 'JumpBoxSecurityGroup'
  JumpBoxAllowInboundSSHFromInternet:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      GroupId: !Ref JumpBoxSecurityGroup
      IpProtocol: tcp
      FromPort: 22
      ToPort: 22
      CidrIp: 0.0.0.0/0
  JumpBoxAllowInboundICMPFromApplication:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      GroupId: !Ref JumpBoxSecurityGroup
      IpProtocol: ICMP
      Description: "Allow ICMP traffic"
      FromPort: -1
      ToPort: -1
      SourceSecurityGroupId: !Ref ApplicationSecurityGroup
  JumpBoxAllowOutboundSSHToWebServer:
    Type: AWS::EC2::SecurityGroupEgress
    Properties:
      GroupId: !Ref JumpBoxSecurityGroup
      IpProtocol: tcp
      FromPort: 22
      ToPort: 22
      DestinationSecurityGroupId: !Ref WebServerSecurityGroup
  JumpBoxAllowOutboundAllICMP:
    Type: AWS::EC2::SecurityGroupEgress
    Properties:
      GroupId: !Ref JumpBoxSecurityGroup
      IpProtocol: ICMP
      FromPort: -1
      ToPort: -1
      CidrIp: 0.0.0.0/0

  #Web server instance security group and its inbound & outbound rules
  WebServerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription:
        !Sub 'Internal Security group for Web Server'
      VpcId: {'Fn::ImportValue': !Sub '${vpcstack}-vpcid'} 
        # - Fn::ImportValue: Fn::Sub: ${vpcstack}-vpcid
      Tags:
        - Key: Name
          Value: !Sub 'WebServerSecurityGroup'
  WebServerAllowInboundSSHFromJumpBox:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      GroupId: !Ref WebServerSecurityGroup
      IpProtocol: tcp
      FromPort: 22
      ToPort: 22
      SourceSecurityGroupId: !Ref JumpBoxSecurityGroup

  #App server instance security group and its inbound & outbound rules
  ApplicationSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription:
        !Sub 'Internal Security group for App Server'
      VpcId: {'Fn::ImportValue': !Sub '${vpcstack}-vpcid'} 
        # - Fn::ImportValue: Fn::Sub: ${vpcstack}-vpcid
      SecurityGroupEgress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: !Ref DBSubnetACidr
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: !Ref DBSubnetBCidr        
      Tags:
        - Key: Name
          Value: !Sub 'ApplicationSecurityGroup'
  ApplicationAllowInboundSSHFromJumpBox:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      GroupId: !Ref ApplicationSecurityGroup
      IpProtocol: tcp
      FromPort: 22
      ToPort: 22
      SourceSecurityGroupId: !Ref JumpBoxSecurityGroup
  ApplicationAllowOutboundICMPToJumpBox:
    Type: AWS::EC2::SecurityGroupEgress
    Properties:
      GroupId: !Ref ApplicationSecurityGroup
      IpProtocol: ICMP
      Description: "Allow ICMP traffic"
      FromPort: -1
      ToPort: -1
      DestinationSecurityGroupId: !Ref JumpBoxSecurityGroup 